#! groovy
pipeline {
  agent {
    label 'kube-m1'
  }
  parameters {
    string(name: 'SERVICE', defaultValue: 'itotko-dk', description: 'Name of service')
    
    string(name: 'NUMBER', defaultValue: '3', description: 'Amount of servers')
  }
  stages {
    stage('Build') {
      steps {
        script {
          sh "docker service scale $SERVICE=0"
          sh "docker service scale $SERVICE=$NUMBER"
        }
      }
    }
  }
}
